CREATE TABLE VEM_SER.PAIS(
ID_PAIS NUMBER NOT NULL,
NOME VARCHAR2(50),
PRIMARY KEY (ID_PAIS)
);

CREATE SEQUENCE VEM_SER.SEQ_PAIS
START WITH 1
INCREMENT BY 1
nocache
nocycle;

CREATE TABLE VEM_SER.ESTADO(
ID_ESTADO NUMBER NOT NULL,
ID_PAIS NUMBER NOT NULL,
NOME VARCHAR(50) NOT NULL,
PRIMARY KEY (ID_ESTADO),
CONSTRAINT FK_ID_PAIS FOREIGN KEY (ID_PAIS) REFERENCES PAIS(ID_PAIS)
);

CREATE SEQUENCE VEM_SER.SEQ_ESTADO
START WITH 1
INCREMENT BY 1
nocache
nocycle;

CREATE TABLE VEM_SER.CIDADE(
ID_CIDADE NUMBER NOT NULL,
ID_ESTADO NUMBER NOT NULL,
NOME VARCHAR2(50),
PRIMARY KEY (ID_CIDADE),
CONSTRAINT FK_ID_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID_ESTADO)
);

CREATE SEQUENCE VEM_SER.SEQ_CIDADE
START WITH 1
INCREMENT BY 1
nocache
nocycle;

CREATE TABLE VEM_SER.BAIRRO(
ID_BAIRRO NUMBER NOT NULL,
ID_CIDADE NUMBER NOT NULL,
ID_ESTADO NUMBER NOT NULL,
NOME VARCHAR2(50) NOT NULL,
PRIMARY KEY (ID_BAIRRO),
CONSTRAINT FK_ID_ESTADO_BAIRRO FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID_ESTADO),
CONSTRAINT FK_ID_CIDADE FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE(ID_CIDADE)
);

CREATE SEQUENCE VEM_SER.SEQ_BAIRRO
START WITH 1
INCREMENT BY 1
nocache
nocycle;

CREATE TABLE VEM_SER.ENDERECO(
ID_ENDERECO NUMBER NOT NULL,
ID_BAIRRO NUMBER NOT NULL,
ID_CIDADE NUMBER NOT NULL,
LOGRADOURO VARCHAR2(255) NOT NULL,
NUMERO NUMBER NOT NULL,
COMPLEMENTO VARCHAR2(100),
CEP VARCHAR2(9),
PRIMARY KEY(ID_ENDERECO),
CONSTRAINT FK_ID_CIDADE_ENDERECO FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE(ID_CIDADE),
CONSTRAINT FK_ID_BAIRRO FOREIGN KEY (ID_BAIRRO) REFERENCES BAIRRO(ID_BAIRRO)
);



CREATE SEQUENCE VEM_SER.SEQ_ENDERECO
START WITH 1
INCREMENT BY 1
nocache
nocycle;

INSERT INTO PAIS (ID_PAIS, NOME) VALUES (SEQ_PAIS.NEXTVAL, 'BRASIL')
INSERT INTO PAIS (ID_PAIS, NOME) VALUES (SEQ_PAIS.NEXTVAL, 'NOVA ZELÂNDIA')

INSERT INTO ESTADO (ID_ESTADO, ID_PAIS, NOME) VALUES (SEQ_ESTADO.NEXTVAL, 1, 'RIO GRANDE DO SUL')
INSERT INTO ESTADO (ID_ESTADO, ID_PAIS, NOME) VALUES (SEQ_ESTADO.NEXTVAL, 1, 'PARANÁ')
INSERT INTO ESTADO (ID_ESTADO, ID_PAIS, NOME) VALUES (SEQ_ESTADO.NEXTVAL, 2, 'OTAGO')
INSERT INTO ESTADO (ID_ESTADO, ID_PAIS, NOME) VALUES (SEQ_ESTADO.NEXTVAL, 2, 'SOUTHLAND')

INSERT INTO CIDADE (ID_CIDADE, ID_ESTADO, NOME) VALUES (SEQ_CIDADE.NEXTVAL, 1, 'PORTO ALEGRE')
INSERT INTO CIDADE (ID_CIDADE, ID_ESTADO, NOME) VALUES (SEQ_CIDADE.NEXTVAL, 2, 'MARINGÁ')
INSERT INTO CIDADE (ID_CIDADE, ID_ESTADO, NOME) VALUES (SEQ_CIDADE.NEXTVAL, 3, 'QUEENSTOWN')
INSERT INTO CIDADE (ID_CIDADE, ID_ESTADO, NOME) VALUES (SEQ_CIDADE.NEXTVAL, 4, 'INVERCARGILL')

INSERT INTO BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME) VALUES (SEQ_BAIRRO.NEXTVAL, 1, 1, 'JARDIM BOTANICO')
INSERT INTO BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME) VALUES (SEQ_BAIRRO.NEXTVAL, 2, 2, 'ZONA 7')
INSERT INTO BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME) VALUES (SEQ_BAIRRO.NEXTVAL, 3, 3, 'LAKE HAWEA')
INSERT INTO BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME) VALUES (SEQ_BAIRRO.NEXTVAL, 4, 4, 'WINDSOR')

INSERT INTO ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) VALUES (SEQ_ENDERECO.NEXTVAL, 1, 1, 'Rua Dr. Salvador França', 1427, 'Parque', 90690000);
INSERT INTO ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) VALUES (SEQ_ENDERECO.NEXTVAL, 1, 1, 'Tv. Serafim Terra', 62, 'Restaurante', 90690280);
INSERT INTO ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) VALUES (SEQ_ENDERECO.NEXTVAL, 2, 2, 'Av. Prudente de Morais', 601, 'Mercado', 87020010);
INSERT INTO ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) VALUES (SEQ_ENDERECO.NEXTVAL, 2, 2, 'Av. Herval', 1250, 'Loja', 87030090);
INSERT INTO ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) VALUES (SEQ_ENDERECO.NEXTVAL, 3, 3, 'Sarges Ways', 0, 'Loja', 9382);
INSERT INTO ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) VALUES (SEQ_ENDERECO.NEXTVAL, 3, 3, 'Noema Terrace', 84, 'Turismo', 9382);
INSERT INTO ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) VALUES (SEQ_ENDERECO.NEXTVAL, 4, 4, 'Chelmsford Street', 147, 'Casa', 9810);
INSERT INTO ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) VALUES (SEQ_ENDERECO.NEXTVAL, 4, 4, 'Wilton Street', 86, 'Casa', 9810)

SELECT * FROM PAIS
SELECT * FROM ESTADO
SELECT * FROM CIDADE
SELECT * FROM BAIRRO
SELECT * FROM ENDERECO